version: 2
updates:
  # تحديثات npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  # التحقق يوميًا
    # إضافة خيارات لتجنب تعارضات الإصدارات
    allow:
      - dependency-name: "*"  # السماح بجميع الحزم
        dependency-type: "all"  # التبعيات العادية والتطويرية
    # تجاهل بعض الحزم إذا لزم الأمر
    ignore:
      - dependency-name: "eslint"  # تجاهل eslint لتجنب التعارض
        versions: ["8.x.x"]  # تجاهل الإصدار 8.x.x
      - dependency-name: "@typescript-eslint/parser"
        versions: ["4.x.x"]  # تجاهل الإصدار 4.x.x

  # تحديثات Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"  # التحقق أسبوعيًا

  # تحديثات GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  # التحقق أسبوعيًا